apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: longusername1234-poi-map-app-dev
  annotations:
    argocd/app-name: longusername1234-poi-map-app-dev
    backstage.io/kubernetes-id: longusername1234-poi-map-app
    backstage.io/kubernetes-namespace: longusername1234
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/longusername1234-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/longusername1234/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/longusername1234/deployments/longusername1234-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/longusername1234-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://longusername1234-poi-map-app-longusername1234.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-longusername1234
  consumesApis:
    - gateway-api-longusername1234
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-longusername1234
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
